"""The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

kolejne = 1
lista_kolejnych = []
dzielniki = []
sekwencja = []

while len(dzielniki) <= 500:
    print(kolejne)
    dzielniki = []
    sekwencja = []
    lista_kolejnych.append(kolejne)  # dodaje kolejne liczby naturalne do lista_kolejnych
    sekwencja.append(sum(lista_kolejnych))
    for liczba in sekwencja:
        for dzielnik in range(1, liczba + 1):
            if liczba % dzielnik == 0:
                dzielniki.append(dzielnik)
    # if len(dzielniki) > 500:
    #     print(f'Najwieksza liczba {sekwencja}, która ma ponad 500 dzielników {dzielniki}')
    print(f'{sekwencja}: {dzielniki}')
    kolejne += 1

print(f'OSTATNI WYNIK::::{sekwencja}: {dzielniki}')