"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms."""


i1 = 1
i2 = 2
lista = []

while i2 < 4000000:
    value = i1 + i2
    i1 = i2
    i2 = value
    if i2 % 2 == 0:
        lista.append(i2)
    # print(i1)
    # print(i2)
    print(value)

print("XXX")
print(lista)
print(sum(lista))
